#!/bin/bash

#########################
#author : nikhil
#date: 6 march
#version: v1
#
#this script will report the aws resource usage
########################

echo "========================================"
echo "REPORT GENERATED ON: $(date '+%Y-%m-%d %H:%M:%S')"
echo "========================================"

set -x


# aws list s3
echo "print list of s3 buckets"
aws s3 ls

# aws list ec2
echo "print list of ec2 instance"
aws ec2 describe-instances --region eu-north-1 --query 'Reservations[*].Instances[*].InstanceId' --output text

# aws list lambda
echo "print list of lambda"
aws lambda list-functions

# aws iam users
echo "print list of iam users"
aws iam list-users | jq -r '.Users[].UserId'
