#!/bin/bash

#########################
# Author : Nikhil
# Updated by : Yugi
# Date : 10 March
# Version : v2
#
# This script generates AWS resource usage report,
# saves it to a log file and sends it via AWS SES
#########################

# variables
DATE=$(date '+%Y-%m-%d_%H-%M-%S')
REPORT_FILE="/home/ubuntu/aws_logs/aws_report.log~"
MANAGER_EMAIL="nikhilhntr@gmail.com"
SENDER_EMAIL="yugandharreddy0258@gmail.com"

echo "Generating AWS Report..."

{
echo "========================================"
echo "REPORT GENERATED ON: $(date '+%Y-%m-%d %H:%M:%S')"
echo "========================================"

echo ""
echo "----------- S3 Buckets -----------"
aws s3 ls

echo ""
echo "----------- EC2 Instances -----------"
aws ec2 describe-instances \
--region eu-north-1 \
--query 'Reservations[*].Instances[*].InstanceId' \
--output text

echo ""
echo "----------- Lambda Functions -----------"
aws lambda list-functions --query 'Functions[*].FunctionName' --output text

echo ""
echo "----------- IAM Users -----------"
aws iam list-users | jq -r '.Users[].UserName'

} > $REPORT_FILE


echo "Report saved to $REPORT_FILE"

REPORT=$(cat $REPORT_FILE)

# send email using AWS SES
aws ses send-email \
--from "$SENDER_EMAIL" \
--destination "ToAddresses=$MANAGER_EMAIL" \
--message "Subject={Data=AWS Resource Report},Body={Text={Data=\"$REPORT\"}}"

echo "Email sent to manager"
